apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  labels:
    app: mariadb
data:
  # my.cnf: |
  #   [mysqld]

  users.sql: |
    RESET MASTER;

    CREATE USER 'maxuser'@'127.0.0.1' IDENTIFIED BY 'maxpwd';
    CREATE USER 'maxuser'@'%' IDENTIFIED BY 'maxpwd';
    GRANT ALL ON *.* TO 'maxuser'@'127.0.0.1' WITH GRANT OPTION;
    GRANT ALL ON *.* TO 'maxuser'@'%' WITH GRANT OPTION;

    SET GLOBAL gtid_strict_mode=ON;

  replication.sql: |
    RESET MASTER;
    STOP SLAVE;
    SET GLOBAL gtid_slave_pos='0-3000-0';
    CHANGE MASTER TO 
        MASTER_HOST='mariadb-0.mariadb-svc.mariadb-dev.svc.cluster.local', 
        MASTER_PORT=3306, 
        MASTER_USER='maxuser', 
        MASTER_PASSWORD='maxpwd',
        MASTER_USE_GTID=slave_pos;  
    START SLAVE;
    SET GLOBAL gtid_strict_mode=ON;

  master-start-replication.sql: |
    RESET MASTER;
    STOP SLAVE;
    SET GLOBAL gtid_slave_pos='0-3000-0';
    CHANGE MASTER TO 
        MASTER_HOST='localhost', 
        MASTER_PORT=3306, 
        MASTER_USER='maxuser', 
        MASTER_PASSWORD='maxpwd',
        MASTER_USE_GTID=slave_pos;
    START SLAVE;
    SET GLOBAL gtid_strict_mode=ON;

  start-mariadb.sh: |
    [[ $(hostname) =~ -([0-9]+)$ ]] || exit 1
    export server_id=${BASH_REMATCH[1]}
    cat /mnt/config-map/users.sql > docker-entrypoint-initdb.d/init.sql
    if [ "$server_id" -eq 0 ]; then
      cat /mnt/config-map/master-start-replication.sql >> docker-entrypoint-initdb.d/init.sql
    else
      cat /mnt/config-map/replication.sql >> docker-entrypoint-initdb.d/init.sql
    fi
    /usr/local/bin/docker-entrypoint.sh mysqld \
      --relay-log=relaylog \
      --log-bin=mariadb-bin \
      --binlog-format=ROW \
      --server-id=$((3000 + $server_id)) \
      --log-slave-updates=1 \
      --gtid-strict-mode=1 \
      --innodb-flush-method=fsync
