apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-maxscale-config
  labels:
    app: maxscale
data:
  maxscale.cnf: |
    [maxscale]
    threads=auto
    admin_host=0.0.0.0

    [server1]
    type=server
    address=mariadb-0.mariadb-svc.dev-mariadb.svc.cluster.local
    port=3306
    protocol=mariadbbackend

    [server2]
    type=server
    address=mariadb-1.mariadb-svc.dev-mariadb.svc.cluster.local
    port=3306
    protocol=mariadbbackend

    [server3]
    type=server
    address=mariadb-2.mariadb-svc.dev-mariadb.svc.cluster.local
    port=3306
    protocol=mariadbbackend

    # Monitor for the servers
    # This will keep MaxScale aware of the state of the servers.
    # MySQL Monitor documentation:
    # https://github.com/mariadb-corporation/MaxScale/blob/2.3/Documentation/Monitors/MariaDB-Monitor.md

    # replication_user と replication_password が未設定の場合、
    # フェイルオーバー時に組まれるレプリケーションは
     #user で設定された maxscale ユーザーでレプリケーションが組まれます

    [MariaDB-Monitor]
    type=monitor
    module=mariadbmon
    servers=server1,server2,server3
    user=maxuser
    password=maxpwd
    auto_failover=true
    auto_rejoin=true
    enforce_read_only_slaves=1
    monitor_interval=2000

    # Service definitions
    # Service Definition for a read-only service and a read/write splitting service.

    # ReadConnRoute documentation:
    # https://github.com/mariadb-corporation/MaxScale/blob/2.3/Documentation/Routers/ReadConnRoute.md

    [Read-Only-Service]
    type=service
    router=readconnroute
    servers=server1,server2,server3
    user=maxuser
    password=maxpwd
    router_options=slave

    # ReadWriteSplit documentation:
    # https://github.com/mariadb-corporation/MaxScale/blob/2.3/Documentation/Routers/ReadWriteSplit.md

    [Read-Write-Service]
    type=service
    router=readwritesplit
    servers=server1,server2,server3
    user=maxuser
    password=maxpwd
    master_failure_mode=fail_on_write

    # Listener definitions for the services
    # Listeners represent the ports the services will listen on.

    [Read-Only-Listener]
    type=listener
    service=Read-Only-Service
    protocol=mariadbclient
    port=4008

    [Read-Write-Listener]
    type=listener
    service=Read-Write-Service
    protocol=mariadbclient
    port=4006

  start-maxscale-instance.sh: |
    cp /mnt/config-template/maxscale.cnf /mnt/config-map/maxscale.cnf
    maxscale -d -U maxscale --configdir=/mnt/config-map -lstdout
