apiVersion: v1
kind: Service
metadata:
  name: maria-acc-svc
  labels:
    app: maxscale
spec:
  selector:
    app: maxscale
  clusterIP: None
  ports:
  - name: read-write
    port: 4006
    targetPort: 4006
  - name: read-only
    port: 4008
    targetPort: 4008
  - name: rest-api
    port: 8989
    targetPort: 8989
