apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: btv-backing
spec:
  selector: 
    name: redis
  type: NodePort  
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31379
